apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: airbnb-clone
data:
  KAFKA_BROKERS: "kafka-0.kafka.airbnb-clone.svc.cluster.local:29092"
  KAFKA_REQUEST_TOPIC: "booking-requests"
  KAFKA_RESPONSE_TOPIC: "booking-updates"

